import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { and, eq, isNull } from "drizzle-orm";
import { ThemeProvider } from "next-themes";
import { auth } from "@/lib/auth/auth";
import { db } from "@/lib/db";
import { themes } from "@/lib/db/schema";
import { paletteToCssDeclarations, type ComputedPalette } from "@/lib/theme/derive-palette";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth.api.getSession({ headers: await headers() });

  let activeTheme: { slug: string; lightPalette: ComputedPalette; darkPalette: ComputedPalette } | null = null;
  if (session?.user.themeId) {
    const [theme] = await db
      .select()
      .from(themes)
      .where(and(eq(themes.id, session.user.themeId), isNull(themes.deletedAt)));
    if (theme) {
      activeTheme = {
        slug: theme.slug,
        lightPalette: theme.lightPalette as ComputedPalette,
        darkPalette: theme.darkPalette as ComputedPalette,
      };
    }
  }

  return (
    <html
      lang="en"
      data-theme={activeTheme?.slug}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {activeTheme ? (
        <head>
          <style>{`
            [data-theme="${activeTheme.slug}"] { ${paletteToCssDeclarations(activeTheme.lightPalette)} }
            [data-theme="${activeTheme.slug}"].dark { ${paletteToCssDeclarations(activeTheme.darkPalette)} }
          `}</style>
        </head>
      ) : null}
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme={session?.user.colorMode ?? "system"} enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
