import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { and, eq, isNull } from "drizzle-orm";
import { ThemeProvider } from "next-themes";
import { auth } from "@/lib/auth/auth";
import { db } from "@/lib/db";
import { themes } from "@/lib/db/schema";
import { paletteToCssDeclarations, type ComputedPalette } from "@/lib/theme/derive-palette";
import { fontVariableClassNames, resolveFontCssVariable } from "@/lib/theme/fonts";
import { getAppSettings } from "@/lib/settings/app-settings";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const settings = await getAppSettings();
  return {
    title: settings.appName,
    description: "Generated by create next app",
  };
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const [session, settings] = await Promise.all([
    auth.api.getSession({ headers: await headers() }),
    getAppSettings(),
  ]);

  let activeTheme: { slug: string; lightPalette: ComputedPalette; darkPalette: ComputedPalette } | null = null;
  if (session?.user.themeId) {
    const [theme] = await db
      .select()
      .from(themes)
      .where(and(eq(themes.id, session.user.themeId), isNull(themes.deletedAt)));
    if (theme) {
      activeTheme = {
        slug: theme.slug,
        lightPalette: theme.lightPalette as ComputedPalette,
        darkPalette: theme.darkPalette as ComputedPalette,
      };
    }
  }

  return (
    <html
      lang="en"
      data-theme={activeTheme?.slug}
      suppressHydrationWarning
      style={
        {
          "--font-sans": resolveFontCssVariable(settings.fontId),
          "--radius": `${settings.borderRadius}rem`,
          fontSize: `${settings.fontScale}%`,
        } as React.CSSProperties
      }
      className={`${fontVariableClassNames()} ${geistMono.variable} h-full antialiased`}
    >
      {activeTheme ? (
        <head>
          <style>{`
            [data-theme="${activeTheme.slug}"] { ${paletteToCssDeclarations(activeTheme.lightPalette)} }
            [data-theme="${activeTheme.slug}"].dark { ${paletteToCssDeclarations(activeTheme.darkPalette)} }
          `}</style>
        </head>
      ) : null}
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme={session?.user.colorMode ?? "system"} enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
